WebApp/Controllers/StudentController.cs
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Data;
using System;
using System.Net;
using System.Web.Mvc;
using BLL.Repositories;
using BOL.Validation_Classes;

namespace WebApp.Controllers
{
    public class StudentController : Controller
    {
        private StudentRepo RepoObj;

        public StudentController()
        {
            RepoObj = new StudentRepo();
        } 

        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            else
            {
                var reas = RepoObj.GetStudentByID(id.Value);
                if (reas == null)
                    return HttpNotFound();
                else
                    return View(reas);
            }
        }

        public ActionResult Create()
        {
            ViewBag.Classes = RepoObj.GetAllClasses();
            ViewBag.Genders = RepoObj.GetAllGenders();
            return View();
        }

        [HttpPost]
        public ActionResult Create(ValidateStudent student)
        {
            if (ModelState.IsValid)
            {
                var reas = RepoObj.InsertStudent(student);
                if (reas)
                {
                    TempData["SuccessMsg"] = "New student added Successfully!";
                    return RedirectToAction("Index");
                }
                else
                {
                    TempData["ErrorMsg"] = "Error on adding new student please try again!";
                    return RedirectToAction("Index");
                }
            }

            ViewBag.Classes = RepoObj.GetAllClasses();
            ViewBag.Genders = RepoObj.GetAllGenders();
            return View(student);
        }

        // GET: Student/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            else
            {
                var reas = RepoObj.GetStudentByID(id.Value);
                if (reas == null)
                    return HttpNotFound();
                else
                {
                    ViewBag.Classes = RepoObj.GetAllClasses();
                    ViewBag.Genders = RepoObj.GetAllGenders();
                    return View(reas);
                }
            }
        }

        [HttpPost]
        public ActionResult Edit(ValidateStudent student)
        {
            if (ModelState.IsValid)
            {
                var reas = RepoObj.UpdateStudent(student);
                if (reas)
                {
                    TempData["SuccessMsg"] = "Student record updated Successfully!";
                    return RedirectToAction("Index");
                }
                else
                {
                    TempData["ErrorMsg"] = "Error on updating student record please try again!";
                    return RedirectToAction("Index");
                }
            }
            ViewBag.Classes = RepoObj.GetAllClasses();
            ViewBag.Genders = RepoObj.GetAllGenders();
            return View(student);
        }

        [AcceptVerbs(HttpVerbs.Post | HttpVerbs.Get)]
        public ActionResult Index(string searchBy, string searchValue)
        {
            IEnumerable<ValidateStudent> reas = RepoObj.GetAllStudents();
            if (string.IsNullOrEmpty(searchValue) && string.IsNullOrEmpty(searchBy))
            {
                TempData["resetF"] = null;
                return View(reas);
            }
            else if (string.IsNullOrEmpty(searchValue))
            {
                TempData["resetF"] = null;
                TempData["InfoMessage"] = "Please provide search value.";
                return View(reas);
            }
            else
            {
                if (searchBy.ToLower() == "std_name")
                {
                    reas = RepoObj.GetAllStudentsFilter(searchValue.ToLower(), null, null);
                    TempData["resetF"] = "data";
                    return View(reas);
                }
                else if (searchBy.ToLower() == "std_phone")
                {
                    reas = RepoObj.GetAllStudentsFilter(null, searchValue.ToLower(), null);
                    TempData["resetF"] = "data";
                    return View(reas);
                }
                else if (searchBy.ToLower() == "classname")
                {
                    reas = RepoObj.GetAllStudentsFilter(null, null, searchValue.ToLower());
                    TempData["resetF"] = "data";
                    return View(reas);
                }
            }
            return View(reas);
        }
    }
}

WebApp/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebApp.Controllers
{
    public class UserController : Controller
    {
        // GET: User
        [AcceptVerbs(HttpVerbs.Get)]
        public ActionResult SignIn()
        {
            return View();
        }
    }
}

WebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link href="~/Content/Site.css" rel="stylesheet" />
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse" title="more options">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

WebApp/Views/Student/Create.cshtml
@model BOL.Validation_Classes.ValidateStudent

@{
    ViewBag.Title = "Add Student";
}

<h2 class="HeadingStyle">Add New Student</h2>

<style>
    .form-horizontal .form-group {
        margin-left: 0px !important;
        margin-right: 0px !important;
    }
</style>


@using (Html.BeginForm())
{
    <div class="DivStyle" style="padding: 15px;">
        <div class="container">
            <div class="row HeadingInfo" style="padding: 0px !important;">
                <p>Personal Information:</p>
            </div>
        </div>
        <div class="form-horizontal">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="row">
                <div class="col-lg-3 col-md-3 col-xs-6 col-sm-3">
                    <div class="form-group">
                        <p>
                            @Html.LabelFor(model => model.std_Fname, htmlAttributes: new { @class = "control-label" })
                            @Html.ValidationMessageFor(model => model.std_Fname, "", new { @class = "text-danger" })
                        </p>
                        <p>
                            @Html.EditorFor(model => model.std_Fname, new { htmlAttributes = new { @class = "form-control" } })
                        </p>
                    </div>
                </div>
                <div class="col-lg-3 col-md-3 col-xs-6 col-sm-3">
                    <div class="form-group">
                        <p>
                            @Html.LabelFor(model => model.std_Lname, htmlAttributes: new { @class = "control-label" })
                            @Html.ValidationMessageFor(model => model.std_Lname, "", new { @class = "text-danger" })
                        </p>
                        <p>
                            @Html.EditorFor(model => model.std_Lname, new { htmlAttributes = new { @class = "form-control" } })
                        </p>
                    </div>
                </div>
                <div class="col-lg-3 col-md-3 col-xs-6 col-sm-3">
                    <div class="form-group">
                        <p>
                            @Html.LabelFor(model => model.std_Fathername, htmlAttributes: new { @class = "control-label" })
                            @Html.ValidationMessageFor(model => model.std_Fathername, "", new { @class = "text-danger" })
                        </p>
                        <p>
                            @Html.EditorFor(model => model.std_Fathername, new { htmlAttributes = new { @class = "form-control" } })
                        </p>
                    </div>
                </div>
                <div class="col-lg-3 col-md-3 col-xs-6 col-sm-3">
                    <div class="form-group">
                        <p>
                            @Html.LabelFor(model => model.std_Mothername, htmlAttributes: new { @class = "control-label" })
                            @Html.ValidationMessageFor(model => model.std_Mothername, "", new { @class = "text-danger" })
                        </p>
                        <p>
                            @Html.EditorFor(model => model.std_Mothername, new { htmlAttributes = new { @class = "form-control" } })
                        </p>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-3 col-md-3 col-xs-6 col-sm-3">
                    <div class="form-group">
                        <p>
                            @Html.LabelFor(model => model.std_gender, htmlAttributes: new { @class = "control-label" })
                            @Html.ValidationMessageFor(model => model.std_gender, "", new { @class = "text-danger" })
                        </p>
                        <p>
                            @Html.DropDownListFor(model => model.std_gender, (IEnumerable<SelectListItem>)ViewBag.Genders, htmlAttributes: new { @class = "form-control" })
                        </p>
                    </div>
                </div>
                <div class="col-lg-3 col-md-3 col-xs-6 col-sm-3">
                    <div class="form-group">
                        <p>
                            @Html.LabelFor(model => model.std_phone, htmlAttributes: new { @class = "control-label" })
                            @Html.ValidationMessageFor(model => model.std_phone, "", new { @class = "text-danger" })
                        </p>
                        <p>
                            @Html.EditorFor(model => model.std_phone, new { htmlAttributes = new { @class = "form-control" } })
                        </p>
                    </div>
                </div>
                <div class="col-lg-3 col-md-3 col-xs-6 col-sm-3">
                    <div class="form-group">
                        <p>
                            @Html.LabelFor(model => model.std_address, htmlAttributes: new { @class = "control-label" })
                            @Html.ValidationMessageFor(model => model.std_address, "", new { @class = "text-danger" })
                        </p>
                        <p>
                            @Html.EditorFor(model => model.std_address, new { htmlAttributes = new { @class = "form-control" } })
                        </p>
                    </div>
                </div>
                <div class="col-lg-3 col-md-3 col-xs-6 col-sm-3">
                    <div class="form-group">
                        <p>
                            @Html.LabelFor(model => model.std_email, htmlAttributes: new { @class = "control-label" })
                            @Html.ValidationMessageFor(model => model.std_email, "", new { @class = "text-danger" })
                        </p>
                        <p>
                            @Html.EditorFor(model => model.std_email, new { htmlAttributes = new { @class = "form-control" } })
                        </p>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-3 col-md-3 col-xs-6 col-sm-3">
                    <div class="form-group">
                        <p>
                            @Html.LabelFor(model => model.std_nationality, htmlAttributes: new { @class = "control-label" })
                            @Html.ValidationMessageFor(model => model.std_nationality, "", new { @class = "text-danger" })
                        </p>
                        <p>
                            @Html.EditorFor(model => model.std_nationality, new { htmlAttributes = new { @class = "form-control" } })
                        </p>
                    </div>
                </div>
                <div class="col-lg-3 col-md-3 col-xs-6 col-sm-3">
                    <div class="form-group">
                        <p>
                            @Html.LabelFor(model => model.std_dob, htmlAttributes: new { @class = "control-label" })
                            @Html.ValidationMessageFor(model => model.std_dob, "", new { @class = "text-danger" })
                        </p>
                        <p>
                            @Html.EditorFor(model => model.std_dob, new { htmlAttributes = new { @class = "form-control" } })
                        </p>
                    </div>
                </div>
                <div class="col-lg-3 col-md-3 col-xs-6 col-sm-3">
                    <div class="form-group">
                        <p>
                            @Html.LabelFor(model => model.std_doa, htmlAttributes: new { @class = "control-label" })
                            @Html.ValidationMessageFor(model => model.std_doa, "", new { @class = "text-danger" })
                        </p>
                        <p>
                            @Html.EditorFor(model => model.std_doa, new { htmlAttributes = new { @class = "form-control" } })
                        </p>
                    </div>
                </div>
                <div class="col-lg-3 col-md-3 col-xs-6 col-sm-3">
                    <div class="form-group">
                        <p>
                            @Html.LabelFor(model => model.std_age, htmlAttributes: new { @class = "control-label" })
                            @Html.ValidationMessageFor(model => model.std_age, "", new { @class = "text-danger" })
                        </p>
                        <p>
                            @Html.EditorFor(model => model.std_age, new { htmlAttributes = new { @class = "form-control" } })
                        </p>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-3 col-md-3 col-xs-6 col-sm-3">
                    <div class="form-group">
                        <p>
                            @Html.LabelFor(model => model.std_religion, htmlAttributes: new { @class = "control-label" })
                            @Html.ValidationMessageFor(model => model.std_religion, "", new { @class = "text-danger" })
                        </p>
                        <p>
                            @Html.EditorFor(model => model.std_religion, new { htmlAttributes = new { @class = "form-control" } })
                        </p>
                    </div>
                </div>
                <div class="col-lg-3 col-md-3 col-xs-6 col-sm-3">
                    <div class="form-group">
                        <p>
                            @Html.LabelFor(model => model.std_class_id, "Class", htmlAttributes: new { @class = "control-label" })
                            @Html.ValidationMessageFor(model => model.std_class_id, "", new { @class = "text-danger" })
                        </p>
                        <p>
                            @Html.DropDownListFor(model => model.std_class_id, (IEnumerable<SelectListItem>)ViewBag.Classes, htmlAttributes: new { @class = "form-control" })
                        </p>
                    </div>
                </div>
                <div class="col-lg-3 col-md-3 col-xs-6 col-sm-3">
                    <div class="form-group">
                        <p>
                        </p>
                        <p>
                        </p>
                    </div>
                </div>
                <div class="col-lg-3 col-md-3 col-xs-6 col-sm-3">
                    <div class="form-group">
                        <p>
                        </p>
                        <p>
                        </p>
                    </div>
                </div>
            </div>
            <div class="form-group">
                <div class=" col-lg-12 col-md-12 col-xs-12 col-sm-12" style="padding: 0px">
                    <input type="submit" value="Add Student" class="btn btn-success" />
                </div>
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List of Students", "Index", null, new { @class = "btn btn-info" })
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WebApp/Views/Student/Index.cshtml
@model IEnumerable<BOL.Validation_Classes.ValidateStudent>

@{
    ViewBag.Title = "List of Students";
}

<h2>List of Students</h2>

<div class="row">
    <div class="col-md-12 col-sm-12 col-lg-12">
        @if (TempData["SuccessMsg"] != null)
        {
            <div class="alert alert-info alert-dismissable">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                <i class="icon-info-with-circle"></i><span>@Html.Raw(TempData["SuccessMsg"])</span>
            </div>
        }
        @if (TempData["ErrorMsg"] != null)
        {
            <div class="alert alert-danger alert-dismissable">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                <i class="icon-blocked"></i><span>@Html.Raw(TempData["ErrorMsg"])</span>
            </div>
        }
    </div>
</div>

<p>
    @Html.ActionLink("Add New Student", "Create", null, new { @class = "btn btn-success" })
</p>
<div style="margin: 15px 0px;">
    @using (Html.BeginForm("Index", "Student", FormMethod.Post))
    {
        <table style="box-shadow: none !important;">
            <tr>
                <td>
                    <span><b style="font-size:16px !important">Search By:</b></span>
                </td>
            </tr>
            <tr style="margin-bottom: 10px">
                <td>
                    @Html.RadioButton("searchBy", "std_Name", true, new { style = "margin-bottom: 15px;" })
                    <text style="margin-bottom: 15px;">Student First Name</text> &nbsp;&nbsp;
                    @Html.RadioButton("searchBy", "std_phone")
                    <text>Phone Number</text>&nbsp;&nbsp;
                    @Html.RadioButton("searchBy", "classname")
                    <text>Class Name</text>
                </td>
            </tr>
            <tr>
                <td>
                    <div style="min-width: 100% !important; display: flex !important; ">
                        @Html.TextBox("searchValue", null, new
                   {
                       Class = "form-control",
                       Required = "Required",
                       placeholder = "Enter Student Name or Phone Number or Class",
                       style = "min-width: 400px !important; margin-right: 20px !important; "
                   })
                        <input type="submit" value="Search" class="btn btn-warning" />
                        @if (TempData["resetF"] != null)
                        {
                            @Html.ActionLink("Reset Search", "Index", null, new { @class = "btn btn-primary", style = "margin-left: 5px;" })
                        }
                    </div>
                </td>
            </tr>
        </table>
    }
</div>
<table class="table">
    <tr class="TableHeader">
        <th style="border-top-left-radius: 8px;">
            @Html.DisplayNameFor(model => model.std_Fname)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.std_Lname)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.std_Fathername)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.std_Mothername)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.std_email)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.std_phone)
        </th>
        <th>
            Class
        </th>
        <th style="border-top-right-radius: 8px;">
            Actions
        </th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.std_Fname)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.std_Lname)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.std_Fathername)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.std_Mothername)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.std_email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.std_phone)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.@class.name) @Html.DisplayFor(modelItem => item.@class.section)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.std_id }, new { @class = "btn btn-primary btn-sm" })
                @Html.ActionLink("Details", "Details", new { id = item.std_id }, new { @class = "btn btn-info btn-sm" })
            </td>
        </tr>
    }

</table>

WebApp/Views/User/SignIn.cshtml
@{
    ViewBag.Title = "Login User";
    Layout = null;
}

<!--===============================================================================================-->
<link rel="icon" type="image/png" href="~/assests/images/icons/favicon.ico" />
<!--===============================================================================================-->
<link rel="stylesheet" type="text/css" href="~/assests/vendor/bootstrap/css/bootstrap.min.css">
<!--===============================================================================================-->
<link rel="stylesheet" type="text/css" href="~/assests/fonts/font-awesome-4.7.0/css/font-awesome.min.css">
<!--===============================================================================================-->
<link rel="stylesheet" type="text/css" href="~/assests/fonts/Linearicons-Free-v1.0.0/icon-font.min.css">
<!--===============================================================================================-->
<link rel="stylesheet" type="text/css" href="~/assests/vendor/animate/animate.css">
<!--===============================================================================================-->
<link rel="stylesheet" type="text/css" href="~/assests/vendor/css-hamburgers/hamburgers.min.css">
<!--===============================================================================================-->
<link rel="stylesheet" type="text/css" href="~/assests/vendor/animsition/css/animsition.min.css">
<!--===============================================================================================-->
<link rel="stylesheet" type="text/css" href="~/assests/vendor/select2/select2.min.css">
<!--===============================================================================================-->
<link rel="stylesheet" type="text/css" href="~/assests/vendor/daterangepicker/daterangepicker.css">
<!--===============================================================================================-->
<link rel="stylesheet" type="text/css" href="~/assests/css/util.css">
<link rel="stylesheet" type="text/css" href="~/assests/css/main.css">
<!--===============================================================================================-->

<div class="limiter">
    <div class="container-login100">
        <div class="wrap-login100">
            @using (Html.BeginForm("Login", "User", FormMethod.Post, new { @class = "login100-form validate-form" }))
            {
                <span class="login100-form-title p-b-43">
                    Login to continue
                </span>


                <div class="wrap-input100 validate-input" data-validate="Valid email is required: ex@abc.xyz">
                    <input class="input100" type="text" name="email">
                    <span class="focus-input100"></span>
                    <span class="label-input100">Email</span>
                </div>


                <div class="wrap-input100 validate-input" data-validate="Password is required">
                    <input class="input100" type="password" name="pass">
                    <span class="focus-input100"></span>
                    <span class="label-input100">Password</span>
                </div>

                <div class="flex-sb-m w-full p-t-3 p-b-32">
                    <div class="contact100-form-checkbox">
                        <input class="input-checkbox100" id="ckb1" type="checkbox" name="remember-me">
                        <label class="label-checkbox100" for="ckb1">
                            Remember me
                        </label>
                    </div>

                    <div>
                        <a href="#" class="txt1">
                            Forgot Password?
                        </a>
                    </div>
                </div>


                <div class="container-login100-form-btn">
                    <button class="login100-form-btn">
                        Login
                    </button>
                </div>

                <div class="text-center p-t-46 p-b-20">
                    <span class="txt2">
                        or sign up using
                    </span>
                </div>

                <div class="login100-form-social flex-c-m">
                    <a href="#" class="login100-form-social-item flex-c-m bg1 m-r-5">
                        <i class="fa fa-facebook-f" aria-hidden="true"></i>
                    </a>

                    <a href="#" class="login100-form-social-item flex-c-m bg2 m-r-5">
                        <i class="fa fa-twitter" aria-hidden="true"></i>
                    </a>
                </div>
            }
            <div class="login100-more" style="background-image: url('../../assests/images/undraw_Educator_re_ju47.png');">
            </div>
        </div>
    </div>
</div>

<!--===============================================================================================-->
<script src="~/assests/vendor/jquery/jquery-3.2.1.min.js"></script>
<!--===============================================================================================-->
<script src="~/assests/vendor/animsition/js/animsition.min.js"></script>
<!--===============================================================================================-->
<script src="~/assests/vendor/bootstrap/js/popper.js"></script>
<script src="~/assests/vendor/bootstrap/js/bootstrap.min.js"></script>
<!--===============================================================================================-->
<script src="~/assests/vendor/select2/select2.min.js"></script>
<!--===============================================================================================-->
<script src="~/assests/vendor/daterangepicker/moment.min.js"></script>
<script src="~/assests/vendor/daterangepicker/daterangepicker.js"></script>
<!--===============================================================================================-->
<script src="~/assests/vendor/countdowntime/countdowntime.js"></script>
<!--===============================================================================================-->
<script src="~/assests/js/main.js"></script>